apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: mdc-simple-rest-api-build
spec:
  serviceAccountName: builder-serviceaccount
  source:
    git:
      url: https://github.com/bbousquet-xebia/mdc-simple-rest-api.git
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: gcr.io/coding-archi-ops/mdc-simple-rest-api

