apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: mdc-simple-rest-api
  namespace: default
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: gcr.io/coding-archi-ops/mdc-simple-rest-api
        env:
        - name: PROJECT_VERSION
          value: "v1"
        - name: TARGET
          value: "Spring Boot Sample v2"
